//BLOGS
export const FETCH_BLOGS_REQUEST = "blogs/FETCH_BLOGS_REQUEST";
export const FETCH_BLOGS_DATA = "blogs/FETCH_BLOGS_DATA";
export const FETCH_BLOGS_DATA_SUCCESS = "blogs/FETCH_BLOGS_DATA_SUCCESS";
export const FETCH_BLOGS_DATA_FAILURE = "blogs/FETCH_BLOG_DATA_FAILURE";