const MODEL = "celebrity-subscriptions-benefits";

export const LIST_SUBSCRIPTION_BENEFITS_REQUEST = `${MODEL}/LIST_SUBSCRIPTION_BENEFITS_REQUEST`;
export const LIST_SUBSCRIPTION_BENEFITS_REQUEST_SUCCESS = `${MODEL}/LIST_SUBSCRIPTION_BENEFITS_REQUEST_SUCCESS`;
export const LIST_SUBSCRIPTION_BENEFITS_REQUEST_FAILURE = `${MODEL}/LIST_SUBSCRIPTION_BENEFITS_REQUEST_FAILURE`;
export const LIST_SUBSCRIPTION_BENEFITS_REQUEST_COMPLETED = `${MODEL}/LIST_SUBSCRIPTION_BENEFITS_REQUEST_COMPLETED`;

export const SET_LIST_SUBSCRIPTION_BENEFITS_OFFSET = `${MODEL}/SET_LIST_SUBSCRIPTION_BENEFITS_OFFSET`;
