export const LIST_SUBSCRIPTION_BENEFITS_REQUEST =
  "celebrity-subscriptions-benefits/LIST_SUBSCRIPTION_BENEFITS_REQUEST";
export const LIST_SUBSCRIPTION_BENEFITS_REQUEST_SUCCESS =
  "celebrity-subscriptions-benefits/LIST_SUBSCRIPTION_BENEFITS_REQUEST_SUCCESS";
export const LIST_SUBSCRIPTION_BENEFITS_REQUEST_FAILURE =
  "celebrity-subscriptions-benefits/LIST_SUBSCRIPTION_BENEFITS_REQUEST_FAILURE";
export const LIST_SUBSCRIPTION_BENEFITS_REQUEST_COMPLETED =
  "celebrity-subscriptions-benefits/LIST_SUBSCRIPTION_BENEFITS_REQUEST_COMPLETED";
