const MODEL = "discount-coupons";

export const GET_DISCOUNT_COUPONS_BANNER = `${MODEL}/GET_DISCOUNT_COUPONS_BANNER`;
export const GET_DISCOUNT_COUPONS_BANNER_SUCCESS = `${MODEL}/GET_DISCOUNT_COUPONS_BANNER_SUCCESS`;
export const GET_DISCOUNT_COUPONS_BANNER_FAILURE = `${MODEL}/GET_DISCOUNT_COUPONS_BANNER_FAILURE`;
export const GET_DISCOUNT_COUPONS_BANNER_COMPLETED = `${MODEL}/GET_DISCOUNT_COUPONS_BANNER_COMPLETED`;
