// CONTRACT_REVIEWS
export const FETCH_CONTRACT_REVIEWS_REQUEST = "contract-reviews/FETCH_CONTRACT_REVIEWS_REQUEST";
export const FETCH_CONTRACT_REVIEWS_REQUEST_SUCCESS = "contract-reviews/FETCH_CONTRACT_REVIEWS_REQUEST_SUCCESS";
export const FETCH_CONTRACT_REVIEWS_REQUEST_FAILURE = "contract-reviews/FETCH_CONTRACT_REVIEWS_REQUEST_FAILURE";
export const FETCH_CONTRACT_REVIEWS_REQUEST_COMPLETED = "contract-reviews/FETCH_CONTRACT_REVIEWS_REQUEST_COMPLETED";

export const GET_CONTRACT_REVIEW_REQUEST = "contract-reviews/GET_CONTRACT_REVIEW_REQUEST";
export const GET_CONTRACT_REVIEW_REQUEST_SUCCESS = "contract-reviews/GET_CONTRACT_REVIEW_REQUEST_SUCCESS";
export const GET_CONTRACT_REVIEW_REQUEST_FAILURE = "contract-reviews/GET_CONTRACT_REVIEW_REQUEST_FAILURE";
export const GET_CONTRACT_REVIEW_REQUEST_COMPLETED = "contract-reviews/GET_CONTRACT_REVIEW_REQUEST_COMPLETED";
