export const AVAILABLE_PAYMENTS_METHODS = {
  CREDIT_CARD: "Tarjeta de Crédito",
  DEBIT_CARD: "Tarjeta de Débito",
  BANK_TRANSFER: "Transferencia Bancaria",
  TICKET: "Efectivo",
  PAYPAL: "Paypal",
};

export const AVAILABLE_PAYMENTS_METHOD_PAYPAL = ["PAYPAL"] as const;

export const AVAILABLE_PAYMENTS_METHOD_STRIPE = ["STRIPE"] as const;
export const AVAILABLE_PAYMENTS_METHOD_SPREEDLY = ["SPREEDLY"] as const;

export const AVAILABLE_PAYMENTS_METHODS_DLOCAL = [
  "CREDIT_CARD",
  "DEBIT_CARD",
  "BANK_TRANSFER",
  "TICKET",
] as const;

export const ALL_AVAILABLE_PAYMENTS_METHODS = [
  ...AVAILABLE_PAYMENTS_METHODS_DLOCAL,
  ...AVAILABLE_PAYMENTS_METHOD_PAYPAL,
  ...AVAILABLE_PAYMENTS_METHOD_STRIPE,
  ...AVAILABLE_PAYMENTS_METHOD_SPREEDLY,
] as const;

export const DLOCAL_PAYMENT_METHODS_WITH_CARD_REQUIRED = [
  "DEBIT_CARD",
  "CREDIT_CARD",
];
