export const GIFT_GIVING_CATEGORY_CODE = "2559";
export const ARTS_AND_ENTERTAINMENT_CATEGORY_CODE = "8";
export const VIDEO_MESSAGE_PRODUCT_ID_PREFIX = "VIDEO_MESSAGE_";
export const BACKSTAGE_SUBSCRIPTION_PRODUCT_ID_PREFIX =
  "BACKSTAGE_SUBSCRIPTION_";
