export const hirings = [
  {
    status: 40,
    id: 10077,
    reference: "202103082155-5815414-10077",
    contractType: 1,
    deliveryContact: "german@famosos.com",
    deliveryFrom: "",
    deliveryTo: "German Solano",
    deliveryType: 1,
    instructions:
      "¡Hola Mark Tacher Testing! Soy tu fan y me haces reír mucho. Me encantaría que me dijeras algo chistoso. ¡Gracias!.",
    isPublic: true,
    occasion: "JOKE",
    userId: 462,
    celebrityId: 864,
    paymentDate: "0001-01-01T00:00:00Z",
    stars: 0,
    review: "",
    celebrityData: {
      id: 864,
      username: "marktacher",
      avatar:
        "https://dqb0851cl2gjs.cloudfront.net/celebrities/864/avatar/famosos-videos-personalizados-marktacher-compressed.jpg",
      fullName: "Mark Tacher Testing",
    },
  },
  {
    status: 10,
    id: 10160,
    reference: "202104171832-9813836-10160",
    contractType: 1,
    deliveryContact: "german@famosos.com",
    deliveryFrom: "",
    deliveryTo: "German Solano",
    deliveryType: 1,
    instructions: "¡Hola Fernando Fiore El Presidente  Testing! ",
    isPublic: true,
    occasion: "OTHER",
    userId: 462,
    celebrityId: 8,
    paymentDate: "0001-01-01T00:00:00Z",
    stars: 0,
    review: "",
    celebrityData: {
      id: 8,
      username: "ferfiore",
      avatar:
        "https://dqb0851cl2gjs.cloudfront.net/celebrities/8/avatar/famosos-videos-personalizados-ferfiore-compressed.jpg",
      fullName: "Fernando Fiore El Presidente  Testing",
    },
  },
  {
    status: 20,
    id: 10205,
    reference: "202104221036-7465585-10205",
    contractType: 1,
    deliveryContact: "german@famosos.com",
    deliveryFrom: "",
    deliveryTo: "German Solano",
    deliveryType: 1,
    instructions: "¡Hola Mark Tacher Testing! ",
    isPublic: true,
    occasion: "OTHER",
    userId: 462,
    celebrityId: 864,
    paymentDate: "2021-04-23T16:19:49.502103-04:00",
    stars: 0,
    review: "",
    celebrityData: {
      id: 864,
      username: "marktacher",
      avatar:
        "https://dqb0851cl2gjs.cloudfront.net/celebrities/864/avatar/famosos-videos-personalizados-marktacher-compressed.jpg",
      fullName: "Mark Tacher Testing",
    },
  },
  {
    status: 25,
    id: 10032,
    reference: "202103021701-5747931-10032",
    contractType: 1,
    deliveryContact: "german@famosos.com",
    deliveryFrom: "",
    deliveryTo: "Adrian",
    deliveryType: 1,
    instructions: "¡Hola Mark Tacher Testing! ",
    isPublic: true,
    occasion: "OTHER",
    userId: 462,
    celebrityId: 864,
    paymentDate: "2021-03-02T12:28:55.357837-05:00",
    stars: 0,
    review: "",
    celebrityData: {
      id: 864,
      username: "marktacher",
      avatar:
        "https://dqb0851cl2gjs.cloudfront.net/celebrities/864/avatar/famosos-videos-personalizados-marktacher-compressed.jpg",
      fullName: "Mark Tacher Testing",
    },
  },
];
