// SAVE CELEBRITY_REQUEST
export const SAVE_CELEBRITY_REQUEST_REQUEST = "contracts/SAVE_CELEBRITY_REQUEST_REQUEST";
export const SAVE_CELEBRITY_REQUEST_REQUEST_SUCCESS = "contracts/SAVE_CELEBRITY_REQUEST_REQUEST_SUCCESS";
export const SAVE_CELEBRITY_REQUEST_REQUEST_FAILURE = "contracts/SAVE_CELEBRITY_REQUEST_REQUEST_FAILURE";
export const SAVE_CELEBRITY_REQUEST_REQUEST_COMPLETED = "contracts/SAVE_CELEBRITY_REQUEST_REQUEST_COMPLETED";
