// CELEBRITIES
export const FETCH_CELEBRITIES_REQUEST = "celebrities/FETCH_CELEBRITIES_REQUEST";
export const FETCH_CELEBRITIES_REQUEST_SUCCESS = "celebrities/FETCH_CELEBRITIES_REQUEST_SUCCESS";
export const FETCH_CELEBRITIES_REQUEST_FAILURE = "celebrities/FETCH_CELEBRITIES_REQUEST_FAILURE";
export const FETCH_CELEBRITIES_REQUEST_COMPLETED = "celebrities/FETCH_CELEBRITIES_REQUEST_COMPLETED";

export const GET_CELEBRITY_REQUEST = "celebrities/GET_CELEBRITY_REQUEST";
export const GET_CELEBRITY_REQUEST_SUCCESS = "celebrities/GET_CELEBRITY_REQUEST_SUCCESS";
export const GET_CELEBRITY_REQUEST_FAILURE = "celebrities/GET_CELEBRITY_REQUEST_FAILURE";
export const GET_CELEBRITY_REQUEST_COMPLETED = "celebrities/GET_CELEBRITY_REQUEST_COMPLETED";
