const MODEL = "localization";

export const GET_COUNTRY_CODE_REQUEST = MODEL + "_GET_COUNTRY_CODE_REQUEST";
export const GET_COUNTRY_CODE_REQUEST_SUCCESS =
  MODEL + "_GET_COUNTRY_CODE_REQUEST_SUCCESS";
export const GET_COUNTRY_CODE_REQUEST_FAILURE =
  MODEL + "_GET_COUNTRY_CODE_REQUEST_FAILURE";
export const GET_COUNTRY_CODE_REQUEST_COMPLETED =
  MODEL + "_GET_COUNTRY_CODE_REQUEST_COMPLETED";
