const MODEL = "hirings";

export const FETCH_COMMENT_HIRING = `${MODEL}/FETCH_COMMENT_HIRING`;
export const FETCH_COMMENT_HIRING_SUCCESS = `${MODEL}/FETCH_COMMENT_HIRING_SUCCESS`;
export const FETCH_COMMENT_HIRING_FAILURE = `${MODEL}/FETCH_COMMENT_HIRING_FAILURE`;
export const FETCH_COMMENT_HIRING_COMPLETED = `${MODEL}/FETCH_COMMENT_HIRING_COMPLETED`;

export const GET_PUBLIC_CONTRACT = `${MODEL}/GET_PUBLIC_CONTRACT`;
export const GET_PUBLIC_CONTRACT_SUCCESS = `${MODEL}/GET_PUBLIC_CONTRACT_SUCCESS`;
export const GET_PUBLIC_CONTRACT_FAILURE = `${MODEL}/GET_PUBLIC_CONTRACT_FAILURE`;
export const GET_PUBLIC_CONTRACT_COMPLETED = `${MODEL}/GET_PUBLIC_CONTRACT_COMPLETED`;
