# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      #- npm run test
      - npm run-script build
      - ls -a
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - .next/**/*
    - .npmrc
    - next.config.js
    - package-lock.json
    - package.json
    - public/**/*
    - sentry.client.config.js
    - sentry.properties
    - sentry.server.config.js
    - package-lock.json
