defaults.url=https://sentry.io/
defaults.org=famosos
defaults.project=famosos-com-frontend
auth.token=ca130ed2351f41eb88901f49af05b0db41721c73e8e440729912d4d3c95b49c8
cli.executable=../../../../.npm/_npx/56635/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/bin/sentry-cli
