defaults.url=https://sentry.io/
defaults.org=famosos
defaults.project=famosos-com-frontend
auth.token=cc6471a5f52d4dc1ad10cc765a94411def351e7e65904bdb828eaca2ac700af8
cli.executable=../../../../.npm/_npx/56635/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/bin/sentry-cli
