// COUNTRIES
export const FETCH_COUNTRIES_REQUEST = "restCountries/FETCH_COUNTRIES_REQUEST";
export const FETCH_COUNTRIES_REQUEST_SUCCESS = "restCountries/FETCH_COUNTRIES_REQUEST_SUCCESS";
export const FETCH_COUNTRIES_REQUEST_FAILURE = "restCountries/FETCH_COUNTRIES_REQUEST_FAILURE";
export const FETCH_COUNTRIES_REQUEST_COMPLETED = "restCountries/FETCH_COUNTRIES_REQUEST_COMPLETED";
