// SAVE FILTERS
export const UPDATE_UPDATE_FLOW = "app/UPDATE_UPDATE_FLOW";
export const UPDATE_SELECTED_CATEGORY = "app/UPDATE_SELECTED_CATEGORY";
export const UPDATE_CATEGORIES = "app/UPDATE_CATEGORIES";
export const UPDATE_SELECTED_COUNTRY = "app/UPDATE_SELECTED_COUNTRY";
export const UPDATE_COUNTRIES = "app/UPDATE_COUNTRIES";
