// GET_SESSION
export const GET_SESSION_REQUEST = "session/GET_SESSION_REQUEST";
export const GET_SESSION_REQUEST_SUCCESS =
  "session/GET_SESSION_REQUEST_SUCCESS";
export const GET_SESSION_REQUEST_FAILURE =
  "session/GET_SESSION_REQUEST_FAILURE";
export const GET_SESSION_REQUEST_COMPLETED =
  "session/GET_SESSION_REQUEST_COMPLETED";

// UPDATE_SESSION
export const UPDATE_SESSION_REQUEST = "session/UPDATE_SESSION_REQUEST";
export const UPDATE_SESSION_REQUEST_SUCCESS =
  "session/UPDATE_SESSION_REQUEST_SUCCESS";
export const UPDATE_SESSION_REQUEST_FAILURE =
  "session/UPDATE_SESSION_REQUEST_FAILURE";
export const UPDATE_SESSION_REQUEST_COMPLETED =
  "session/UPDATE_SESSION_REQUEST_COMPLETED";

// V2 TYPES
// GET USER ACCOUNT DETAILS
export const GET_USER_ACCOUNT_DETAILS = "session/GET_USER_ACCOUNT_DETAILS";
export const GET_USER_ACCOUNT_DETAILS_SUCCESS =
  "session/GET_USER_ACCOUNT_DETAILS_SUCCESS";
export const GET_USER_ACCOUNT_DETAILS_FAILURE =
  "session/GET_USER_ACCOUNT_DETAILS_FAILURE";
export const GET_USER_ACCOUNT_DETAILS_COMPLETED =
  "session/GET_USER_ACCOUNT_DETAILS_COMPLETED";

export const GET_USER_CONTRACT_REQUEST = "session/GET_USER_CONTRACT_REQUEST";
export const GET_USER_CONTRACT_REQUEST_SUCCESS =
  "session/GET_USER_CONTRACT_REQUEST_SUCCESS";
export const GET_USER_CONTRACT_REQUEST_FAILURE =
  "session/GET_USER_CONTRACT_REQUEST_FAILURE";
export const GET_USER_CONTRACT_REQUEST_COMPLETED =
  "session/GET_USER_CONTRACT_REQUEST_COMPLETED";
