// SUBSCRIPTION
export const PROCESS_SUBSCRIPTION_REQUEST = "contracts/PROCESS_SUBSCRIPTION_REQUEST";
export const PROCESS_SUBSCRIPTION_REQUEST_SUCCESS =
  "contracts/PROCESS_SUBSCRIPTION_REQUEST_SUCCESS";
export const PROCESS_SUBSCRIPTION_REQUEST_FAILURE =
  "contracts/PROCESS_SUBSCRIPTION_REQUEST_FAILURE";
export const PROCESS_SUBSCRIPTION_REQUEST_COMPLETED =
  "contracts/PROCESS_SUBSCRIPTION_REQUEST_COMPLETED";
