// SUBSCRIPTION
export const PROCESS_SUBSCRIPTION_REQUEST =
  "user_subscriptions/PROCESS_SUBSCRIPTION_REQUEST";
export const PROCESS_SUBSCRIPTION_REQUEST_SUCCESS =
  "user_subscriptions/PROCESS_SUBSCRIPTION_REQUEST_SUCCESS";
export const PROCESS_SUBSCRIPTION_REQUEST_FAILURE =
  "user_subscriptions/PROCESS_SUBSCRIPTION_REQUEST_FAILURE";
export const PROCESS_SUBSCRIPTION_REQUEST_COMPLETED =
  "user_subscriptions/PROCESS_SUBSCRIPTION_REQUEST_COMPLETED";

export const FETCH_USER_SUBSCRIPTIONS_REQUEST =
  "user_subscriptions/FETCH_USER_SUBSCRIPTIONS";
export const FETCH_USER_SUBSCRIPTIONS_SUCCESS =
  "user_subscriptions/FETCH_USER_SUBSCRIPTIONS_SUCCESS";
export const FETCH_USER_SUBSCRIPTIONS_FAILURE =
  "user_subscriptions/FETCH_USER_SUBSCRIPTIONS_FAILURE";
export const FETCH_USER_SUBSCRIPTIONS_COMPLETED =
  "user_subscriptions/FETCH_USER_SUBSCRIPTIONS_COMPLETED";

export const LIST_SUBSCRIPTION_POSTS_REQUEST =
  "user_subscriptions/LIST_SUBSCRIPTION_POSTS_REQUEST";
export const LIST_SUBSCRIPTION_POSTS_REQUEST_SUCCESS =
  "user_subscriptions/LIST_SUBSCRIPTION_POSTS_REQUEST_SUCCESS";
export const LIST_SUBSCRIPTION_POSTS_REQUEST_FAILURE =
  "user_subscriptions/LIST_SUBSCRIPTION_POSTS_REQUEST_FAILURE";
export const LIST_SUBSCRIPTION_POSTS_REQUEST_COMPLETED =
  "user_subscriptions/LIST_SUBSCRIPTION_POSTS_REQUEST_COMPLETED";
