branch-defaults:
  default:
    environment: FamososFrontend-Testing
  duvan:
    environment: FamososFrontend-Testing
  master:
    environment: FamososFrontend-Production
  new-form:
    environment: FamososFrontend-Production
deploy:
  artifact: zip.zip
environment-defaults:
  FamososFrontend-Testing:
    branch: null
    repository: null
global:
  application_name: Famosos - Frontend
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js 12 running
    on 64bit Amazon Linux 2/5.0.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
