export const flashDeliveryCelebritiesUsernames = `alexisayala
  vanessaguzman
  enriquearce
  andrescepeda
  elkomander
  esperanzagomez
  pibevalderrama
  marktacher
  kiko
  jhonnyrivera
  victormunoz
  rolandoschiavi
  juanbaptistad
  alantacher
  juliangil
  fabra
  osmariel
  gustavomunguia
  millonariobm
  martinricca
  vanessaguzman
  faisy
  luisitorey
  elizabethloaiza
  tinoasprilla
  dennisarana
  brujoficial
  kabeto
  manualerod
  pirry
  yeilove
  marioarvizu
  pollitotropical
  luismateus
  jurgendamm
  marcofabian
  aliciamachado
  ferfiore
  herenciadetimbiqui
  geraldinezivic
  ariellevy
  maia
  lilianachupitos
  victordrija
  joseron
  wendygonzalez
  albertsanchez
  testheinz
  jonathanmoly
  gustavoelis
  juanmagan
  gabyspanic
  nelsonkanzela
  abelardo
  isra
  rosendoyroserito
  henrysantos
  fredyvillareal
  fabiolamartinez
  analayevska
  joeresendez
  leiderpreciado
  deboradunhil
  aldofranco
  charlyperez
  goldopasao
  lorenameritano
  alexstrecci
  alexatomas
  jorgiesanchez
  renehiguita
  aleidanunez
  lachicuela
  pabloportillo
  sabrinasabrok
  omarperez
  papanoel
  jhondermorales
  laurayjuan
  alexperea
  jorgevillaveces
  elshowdetato
  barbaraboller
  alonsoescoboza
  nataliacarvajal
  sandramunoz
  dominguero
  puracomediapapa
  veronicamontes
  miaqueen
  robertomateos
  mozartlapara
  milynette
  sabrinasosa
  carlosduran
  osvaldoriosalonso
  luisomartapia
  misticocmll
  luismoncada
  auracris
  mayragoni
  conejotarantini
  juandaroa
  reinaldonavia
  martinliberman
  nesty
  sofiacuello
  jackyfontanez
  tonnyboom
  milaegred
  lasocurrenciasdevictor
  ivanvalenciano9
  victorcamara
  alexvizuete
  santaclausmex
  martinrusso
  aidamartinezw
  zeltzinsuarez
  mayakarunna
  pauloquevedo
  ivanlopez
  grupolemongrass
  gabyplatas
  ramirofumazoni
  johnsutcliffe
  andreinacarmona
  pachorueda
  blasperez
  alexmanga
  tianbz
  yudyarias
  hectorsoberon
  bobbylarios
  juanjopurata
  wendybraga
  homerito
  sandrabeltran
  danipalavecino
  javieragomez
  quikefelman
  mariobazares
  alejandrotommasi
  jennygarcia
  dragonlee
  vincentpelluard
  kristelsakay
  funky
  alansaldana
  yanigianola
  mbrivio
  alediaz
  gutycarrera
  juanaarias
  sharlene
  suzycortez
  golpeagolpe
  santaclaus
  alejandrarivera
  danielavega
  pabloazar
  eduardogarza
  renevelazco
  lauravignatti
  ricardofranco
  cinthyabermudez
  carolinapico
  tanaromero
  shermancardenas
  gabrielmusic
  bibiramirez
  terrible
  mauricioypalodeagua
  xilenaaycardi
  conniepena
  jorgesektacore
  fernando
  andreaquiro
  fernygraciano
  cristianrodriguez
  loscantores
  guadalupediagosti
  jessicachirino
  juanitagomez
  angeliqueblandon
  luludf
  shailaperez
  stephanievaquer
  alejandraherrera
  natalyumana
  katherinaaceto
  reginatiscareno
  esmeraldaorozco
  memoorozco
  zalvadorzerboni
  coquito
  nenequintana
  emilypink
  javierorozco
  alejandraochoa
  carolinapetkoff
  dennisfernando
  natashateen
  michelle2torres
  jesusgama
  alejandrogutierrezz
  lisvega
  mauricioaspe
  adancruz
  alexisayala
  cieloleebrise
  scrop
  pabloheredia
  adriwilliams
  adiccionallabial
  caremonja
  genarocruz
  luisgatica
  gruposuperlamas
  anabelzalazar
  deiviscorrea
  marcelocordoba
  itsdario
  erikamitdank
  sebastianeslava
  dariodario
  anamariacuellar
  pabloceppelini
  nicolasagustin
  alcover
  jabneel100voces
  linacardona
  danielgama
  fernandogonzalez
  davidpalacio
  surosolar
  emblemamc
  veronicaleal
  vielkatv
  laabuela
  edwinherrera
  cokoyamasaki
  manuellamendoza
  ximenapalomino
  farid_diaz
  nachoacero
  candyflow
  mariajosepintor
  dinorahromero
  erikaboveri
  andreschavez
  sebastianllapur
  djanevictoria
  gummerrueda
  danielrene
  danielmunguia
  alexblanco
  juliopitbull
  andreasbook
  paulinadealba
  yeniferquintero
  giuliomottola
  carlionvzla
  lhoanelhijodelrey
  gaona
  lennyfierro
  camilaselser
  marianabeltran
  angelicajaramillo
  ingridaceiton
  yenvideo
  davidreinoso
  lucianasierra
  edgarmendez
  genetorrellas
  andrestorres00
  judacnyrondon
  greciarecinos
  pitodiego
  moisesarizmendi
  johannasolano
  martina
  derian
  karinacalmet
  alexisviera
  israelromero
  barbiemoreno
  vivisantos
  tonydandrades
  julianpereztv
  gonzalovivanco
  patriciavasquez
  danielbonet
  camilotrujillo
  margaritareyes
  sebastiansosa
  itslapalacio
  ladyyuliana
  chiti
  yadranka
  javierbustillos
  dorismar
  kathy
  orianamontero
  aleanger
  thedustinluke
  luiseduardocastro
  tamarabella
  michelgallero
  raquelnunezh
  josecarlosfarrera
  kevinrenteria
  hernanbernadello
  papanoelperu
  gr3ngasho
  stephaniealmeida
  cristianarango
  amandapatricia
  oskarinaconk
  alejandraivanova
  juanmapiano
  andrescohen
  bernardbullen
  rafaelpedroza
  paulasanchez
  paitosan
  karlyfornos
  andreihadler
  atehomanager
  hernanorjuela
  miguelthor
  luigibalestra
  nachodimarco
  tomasignacio
  vivianaguerrero
  alejolittle
  lunamartinez
  millenialde50
  kevinlustgarten
  charly
  valentinaortiz
  manuelavargas
  lasdiosas
  luzdelsolneisa
  elcartelvallenatoec
  luiscampillo
  riveramao
  gibi
  santiagomagnone
  remygaribay
  cotyvazquez
  tibycamacho
  jessicacardona
  alejandrobenzaquen
  arabesincamello
  ebony
  zaira
  dave
  davidkontos
  danielhaddad
  valeriasandovall
  veronicapoveda
  isaalonso
  sergiovergara
  scarlethhdez
  javiherrera
  bozach
  elturcoamar
  andreawarrior
  marchan
  karenrodriguez
  marjoriecooper
  asranadeem`
  .split("\n")
  .map((username) => username.trim());
