// PAYMENT_GATEWAYS
export const FETCH_PAYMENT_GATEWAYS_REQUEST = "paymentGateways/FETCH_PAYMENT_GATEWAYS_REQUEST";
export const FETCH_PAYMENT_GATEWAYS_REQUEST_SUCCESS = "paymentGateways/FETCH_PAYMENT_GATEWAYS_REQUEST_SUCCESS";
export const FETCH_PAYMENT_GATEWAYS_REQUEST_FAILURE = "paymentGateways/FETCH_PAYMENT_GATEWAYS_REQUEST_FAILURE";
export const FETCH_PAYMENT_GATEWAYS_REQUEST_COMPLETED = "paymentGateways/FETCH_PAYMENT_GATEWAYS_REQUEST_COMPLETED";

// CURRENCY_EXCHANGE
export const CURRENCY_EXCHANGE_REQUEST = "paymentGateways/CURRENCY_EXCHANGE_REQUEST";
export const CURRENCY_EXCHANGE_REQUEST_SUCCESS = "paymentGateways/CURRENCY_EXCHANGE_REQUEST_SUCCESS";
export const CURRENCY_EXCHANGE_REQUEST_FAILURE = "paymentGateways/CURRENCY_EXCHANGE_REQUEST_FAILURE";
export const CURRENCY_EXCHANGE_REQUEST_COMPLETED = "paymentGateways/FETCH_PAYMENT_GATEWAYS_REQUEST_COMPLETED";

// GET CONTRACT
export const GET_CONTRACT_TO_PAY_REQUEST = "contracts/GET_CONTRACT_TO_PAY_REQUEST";
export const GET_CONTRACT_TO_PAY_REQUEST_SUCCESS = "contracts/GET_CONTRACT_TO_PAY_REQUEST_SUCCESS";
export const GET_CONTRACT_TO_PAY_REQUEST_FAILURE = "contracts/GET_CONTRACT_TO_PAY_REQUEST_FAILURE";
export const GET_CONTRACT_TO_PAY_REQUEST_COMPLETED = "contracts/GET_CONTRACT_TO_PAY_REQUEST_COMPLETED";

// CREATE CONTRACT PAYMENT
export const CREATE_CONTRACT_PAYMENT_REQUEST = "contracts/CREATE_CONTRACT_PAYMENT_REQUEST";
export const CREATE_CONTRACT_PAYMENT_REQUEST_SUCCESS = "contracts/CREATE_CONTRACT_PAYMENT_REQUEST_SUCCESS";
export const CREATE_CONTRACT_PAYMENT_REQUEST_FAILURE = "contracts/CREATE_CONTRACT_PAYMENT_REQUEST_FAILURE";
export const CREATE_CONTRACT_PAYMENT_REQUEST_COMPLETED = "contracts/CREATE_CONTRACT_PAYMENT_REQUEST_COMPLETED";
