// CELEBRITIES
export const FETCH_CELEBRITIES_REQUEST = "contracts/FETCH_CELEBRITIES_REQUEST";
export const FETCH_CELEBRITIES_REQUEST_SUCCESS =
  "contracts/FETCH_CELEBRITIES_REQUEST_SUCCESS";
export const FETCH_CELEBRITIES_REQUEST_FAILURE =
  "contracts/FETCH_CELEBRITIES_REQUEST_FAILURE";
export const FETCH_CELEBRITIES_REQUEST_COMPLETED =
  "contracts/FETCH_CELEBRITIES_REQUEST_COMPLETED";

export const FETCH_CELEBRITIES_SIMILAR_RESULTS_REQUEST =
  "contracts/FETCH_CELEBRITIES_SIMILAR_RESULTS_REQUEST";
export const FETCH_CELEBRITIES_SIMILAR_RESULTS_REQUEST_SUCCESS =
  "contracts/FETCH_CELEBRITIES_SIMILAR_RESULTS_REQUEST_SUCCESS";
export const FETCH_CELEBRITIES_SIMILAR_RESULTS_REQUEST_FAILURE =
  "contracts/FETCH_CELEBRITIES_SIMILAR_RESULTS_REQUEST_FAILURE";
export const FETCH_CELEBRITIES_SIMILAR_RESULTS_REQUEST_COMPLETED =
  "contracts/FETCH_CELEBRITIES_SIMILAR_RESULTS_REQUEST_COMPLETED";

export const FETCH_REVIEWS_REQUEST = "contracts/FETCH_REVIEWS_REQUEST";
export const FETCH_REVIEWS_REQUEST_SUCCESS =
  "contracts/FETCH_REVIEWS_REQUEST_SUCCESS";
export const FETCH_REVIEWS_REQUEST_FAILURE =
  "contracts/FETCH_REVIEWS_REQUEST_FAILURE";
export const FETCH_REVIEWS_REQUEST_COMPLETED =
  "contracts/FETCH_REVIEWS_REQUEST_COMPLETED";

export const FETCH_PUBLIC_CONTRACTS_REQUEST =
  "contracts/FETCH_PUBLIC_CONTRACTS_REQUEST";
export const FETCH_PUBLIC_CONTRACTS_REQUEST_SUCCESS =
  "contracts/FETCH_PUBLIC_CONTRACTS_REQUEST_SUCCESS";
export const FETCH_PUBLIC_CONTRACTS_REQUEST_FAILURE =
  "contracts/FETCH_PUBLIC_CONTRACTS_REQUEST_FAILURE";
export const FETCH_PUBLIC_CONTRACTS_REQUEST_COMPLETED =
  "contracts/FETCH_PUBLIC_CONTRACTS_REQUEST_COMPLETED";

export const GET_CELEBRITY_REQUEST = "contracts/GET_CELEBRITY_REQUEST";
export const GET_CELEBRITY_REQUEST_SUCCESS =
  "contracts/GET_CELEBRITY_REQUEST_SUCCESS";
export const GET_CELEBRITY_REQUEST_FAILURE =
  "contracts/GET_CELEBRITY_REQUEST_FAILURE";
export const GET_CELEBRITY_REQUEST_COMPLETED =
  "contracts/GET_CELEBRITY_REQUEST_COMPLETED";

export const UPDATE_QUERY_PARAMS = "contracts/UPDATE_QUERY_PARAMS";

export const FETCH_TRENDING_CONTRACTS_REQUEST =
  "contracts/FETCH_TRENDING_CONTRACTS_REQUEST";
export const FETCH_TRENDING_CONTRACTS_REQUEST_SUCCESS =
  "contracts/FETCH_TRENDING_CONTRACTS_REQUEST_SUCCESS";
export const FETCH_TRENDING_CONTRACTS_REQUEST_FAILURE =
  "contracts/FETCH_TRENDING_CONTRACTS_REQUEST_FAILURE";
export const FETCH_TRENDING_CONTRACTS_REQUEST_COMPLETED =
  "contracts/FETCH_TRENDING_CONTRACTS_REQUEST_COMPLETED";

export const PLAY_VIDEO = "contracts/PLAY_VIDEO";

export const SET_PREVIOUS_PATH = "contracts/SET_PREVIOUS_PATH";

export const FETCH_SIMILAR_CELEBRITIES_REQUEST =
  "contracts/FETCH_SIMILAR_CELEBRITIES_REQUEST";
export const FETCH_SIMILAR_CELEBRITIES_REQUEST_SUCCESS =
  "contracts/FETCH_SIMILAR_CELEBRITIES_REQUEST_SUCCESS";
export const FETCH_SIMILAR_CELEBRITIES_REQUEST_FAILURE =
  "contracts/FETCH_SIMILAR_CELEBRITIES_REQUEST_FAILURE";
export const FETCH_SIMILAR_CELEBRITIES_REQUEST_COMPLETED =
  "contracts/FETCH_SIMILAR_CELEBRITIES_REQUEST_COMPLETED";

export const CLEAN_PUBLIC_CONTRACTS = "contracts/CLEAN_PUBLIC_CONTRACTS";

export const FETCH_FLASH_DELIVERY_CELEBRITIES_REQUEST =
  "contracts/FETCH_FLASH_DELIVERY_CELEBRITIES_REQUEST";
export const FETCH_FLASH_DELIVERY_CELEBRITIES_REQUEST_SUCCESS =
  "contracts/FETCH_FLASH_DELIVERY_CELEBRITIES_REQUEST_SUCCESS";
export const FETCH_FLASH_DELIVERY_CELEBRITIES_REQUEST_FAILURE =
  "contracts/FETCH_FLASH_DELIVERY_CELEBRITIES_REQUEST_FAILURE";
export const FETCH_FLASH_DELIVERY_CELEBRITIES_REQUEST_COMPLETED =
  "contracts/FETCH_FLASH_DELIVERY_CELEBRITIES_REQUEST_COMPLETED";

export const FETCH_CELEBRITY_SUBSCRIPTION_PLANS_REQUEST =
  "contracts/FETCH_CELEBRITY_SUBSCRIPTION_PLANS_REQUEST";
export const FETCH_CELEBRITY_SUBSCRIPTION_PLANS_REQUEST_SUCCESS =
  "contracts/FETCH_CELEBRITY_SUBSCRIPTION_PLANS_REQUEST_SUCCESS";
export const FETCH_CELEBRITY_SUBSCRIPTION_PLANS_REQUEST_FAILURE =
  "contracts/FETCH_CELEBRITY_SUBSCRIPTION_PLANS_REQUEST_FAILURE";
export const FETCH_CELEBRITY_SUBSCRIPTION_PLANS_REQUEST_COMPLETED =
  "contracts/FETCH_CELEBRITY_SUBSCRIPTION_PLANS_REQUEST_COMPLETED";
