export const FETCH_CELEBRITIES_SECTIONS =
  "celebrity-sections/FETCH_CELEBRITIES_SECTIONS";
export const FETCH_CELEBRITIES_SECTIONS_SUCCESS =
  "celebrity-sections/FETCH_CELEBRITIES_SECTIONS_SUCCESS";
export const FETCH_CELEBRITIES_SECTIONS_FAILURE =
  "celebrity-sections/FETCH_CELEBRITIES_SECTIONS_FAILURE";
export const FETCH_CELEBRITIES_SECTIONS_COMPLETED =
  "celebrity-sections/FETCH_CELEBRITIES_SECTIONS_COMPLETED";
