// PAYMENT_GATEWAYS
export const FETCH_PAYMENT_GATEWAYS_REQUEST =
  "paymentGateways/FETCH_PAYMENT_GATEWAYS_REQUEST";
export const FETCH_PAYMENT_GATEWAYS_REQUEST_SUCCESS =
  "paymentGateways/FETCH_PAYMENT_GATEWAYS_REQUEST_SUCCESS";
export const FETCH_PAYMENT_GATEWAYS_REQUEST_FAILURE =
  "paymentGateways/FETCH_PAYMENT_GATEWAYS_REQUEST_FAILURE";
export const FETCH_PAYMENT_GATEWAYS_REQUEST_COMPLETED =
  "paymentGateways/FETCH_PAYMENT_GATEWAYS_REQUEST_COMPLETED";

// CURRENCY_EXCHANGE
export const CURRENCY_EXCHANGE_REQUEST =
  "paymentGateways/CURRENCY_EXCHANGE_REQUEST";
export const CURRENCY_EXCHANGE_REQUEST_SUCCESS =
  "paymentGateways/CURRENCY_EXCHANGE_REQUEST_SUCCESS";
export const CURRENCY_EXCHANGE_REQUEST_FAILURE =
  "paymentGateways/CURRENCY_EXCHANGE_REQUEST_FAILURE";
export const CURRENCY_EXCHANGE_REQUEST_COMPLETED =
  "paymentGateways/CURRENCY_EXCHANGE_REQUEST_COMPLETED";

// GET CONTRACT
export const GET_CONTRACT_TO_PAY_REQUEST =
  "contracts/GET_CONTRACT_TO_PAY_REQUEST";
export const GET_CONTRACT_TO_PAY_REQUEST_SUCCESS =
  "contracts/GET_CONTRACT_TO_PAY_REQUEST_SUCCESS";
export const GET_CONTRACT_TO_PAY_REQUEST_FAILURE =
  "contracts/GET_CONTRACT_TO_PAY_REQUEST_FAILURE";
export const GET_CONTRACT_TO_PAY_REQUEST_COMPLETED =
  "contracts/GET_CONTRACT_TO_PAY_REQUEST_COMPLETED";

// CREATE DLOCAL PAYMENT
export const CREATE_DLOCAL_PAYMENT_REQUEST =
  "contracts/CREATE_DLOCAL_PAYMENT_REQUEST";
export const CREATE_DLOCAL_PAYMENT_REQUEST_SUCCESS =
  "contracts/CREATE_DLOCAL_PAYMENT_REQUEST_SUCCESS";
export const CREATE_DLOCAL_PAYMENT_REQUEST_FAILURE =
  "contracts/CREATE_DLOCAL_PAYMENT_REQUEST_FAILURE";
export const CREATE_DLOCAL_PAYMENT_REQUEST_COMPLETED =
  "contracts/CREATE_DLOCAL_PAYMENT_REQUEST_COMPLETED";

// CREATE STRIPE PAYMENT
export const CREATE_STRIPE_PAYMENT_REQUEST =
  "contracts/CREATE_STRIPE_PAYMENT_REQUEST";
export const CREATE_STRIPE_PAYMENT_REQUEST_SUCCESS =
  "contracts/CREATE_STRIPE_PAYMENT_REQUEST_SUCCESS";
export const CREATE_STRIPE_PAYMENT_REQUEST_FAILURE =
  "contracts/CREATE_STRIPE_PAYMENT_REQUEST_FAILURE";
export const CREATE_STRIPE_PAYMENT_REQUEST_COMPLETED =
  "contracts/CREATE_STRIPE_PAYMENT_REQUEST_COMPLETED";

// CREATE PAYPAL PAYMENT
export const CREATE_PAYPAL_PAYMENT_REQUEST =
  "contracts/CREATE_PAYPAL_PAYMENT_REQUEST";
export const CREATE_PAYPAL_PAYMENT_REQUEST_SUCCESS =
  "contracts/CREATE_PAYPAL_PAYMENT_REQUEST_SUCCESS";
export const CREATE_PAYPAL_PAYMENT_REQUEST_FAILURE =
  "contracts/CREATE_PAYPAL_PAYMENT_REQUEST_FAILURE";
export const CREATE_PAYPAL_PAYMENT_REQUEST_COMPLETED =
  "contracts/CREATE_PAYPAL_PAYMENT_REQUEST_COMPLETED";

//DISCOUNT COUPON
export const APPLY_DISCOUNT_COUPON = "user-payments/APPLY_DISCOUNT_COUPONS";
export const APPLY_DISCOUNT_COUPON_SUCCESS =
  "user-payments/APPLY_DISCOUNT_COUPONS_SUCCESS";
export const APPLY_DISCOUNT_COUPON_FAILURE =
  "user-payments/APPLY_DISCOUNT_COUPONS_FAILURE";
export const APLY_DISCOUNT_COUPON_COMPLETED =
  "user-payments/APPLY_DISCOUNT_COUPONS_COMPLETED";
export const APLY_DISCOUNT_COUPON_CLEAR =
  "user-payments/APLY_DISCOUNT_COUPON_CLEAR";

//DLOCAL GET PAYMENTS METHODS
export const FETCH_AVAILABLE_PAYMENT_METHODS_DLOCAL =
  "gateway-payment-methods/FETCH_AVAILABLE_PAYMENT_METHODS_DLOCAL";
export const FETCH_AVAILABLE_PAYMENT_METHODS_DLOCAL_COMPLETED =
  "gateway-payment-methods/FETCH_AVAILABLE_PAYMENT_METHODS_DLOCAL_COMPLETED";
export const FETCH_AVAILABLE_PAYMENT_METHODS_DLOCAL_SUCCESS =
  "gateway-payment-methods/FETCH_AVAILABLE_PAYMENT_METHODS_DLOCAL_SUCCESS";
export const FETCH_AVAILABLE_PAYMENT_METHODS_DLOCAL_FAILURE =
  "gateway-payment-methods/FETCH_AVAILABLE_PAYMENT_METHODS_DLOCAL_FAILURE";
