export const FETCH_LANDINGS = "landings/FETCH_LANDINGS";
export const FETCH_LANDINGS_SUCCESS = "landings/FETCH_LANDINGS_SUCCESS";
export const FETCH_LANDINGS_FAILURE = "landings/FETCH_LANDINGS_FAILURE";
export const FETCH_LANDINGS_COMPLETED = "landings/FETCH_LANDINGS_COMPLETED";
