// SAVE CLIENT CONTRACT
export const SAVE_CLIENT_CONTRACT_REQUEST = "contracts/SAVE_CLIENT_CONTRACT_REQUEST";
export const SAVE_CLIENT_CONTRACT_REQUEST_SUCCESS = "contracts/SAVE_CLIENT_CONTRACT_REQUEST_SUCCESS";
export const SAVE_CLIENT_CONTRACT_REQUEST_FAILURE = "contracts/SAVE_CLIENT_CONTRACT_REQUEST_FAILURE";
export const SAVE_CLIENT_CONTRACT_REQUEST_COMPLETED = "contracts/SAVE_CLIENT_CONTRACT_REQUEST_COMPLETED";

// LIST CLIENT CONTRACTS
export const LIST_CLIENT_CONTRACTS_REQUEST = "contracts/LIST_CLIENT_CONTRACTS_REQUEST";
export const LIST_CLIENT_CONTRACTS_REQUEST_SUCCESS = "contracts/LIST_CLIENT_CONTRACTS_REQUEST_SUCCESS";
export const LIST_CLIENT_CONTRACTS_REQUEST_FAILURE = "contracts/LIST_CLIENT_CONTRACTS_REQUEST_FAILURE";
export const LIST_CLIENT_CONTRACTS_REQUEST_COMPLETED = "contracts/LIST_CLIENT_CONTRACTS_REQUEST_COMPLETED";

// GET CLIENT CONTRACT
export const GET_CLIENT_CONTRACT_REQUEST = "contracts/GET_CLIENT_CONTRACT_REQUEST";
export const GET_CLIENT_CONTRACT_REQUEST_SUCCESS = "contracts/GET_CLIENT_CONTRACT_REQUEST_SUCCESS";
export const GET_CLIENT_CONTRACT_REQUEST_FAILURE = "contracts/GET_CLIENT_CONTRACT_REQUEST_FAILURE";
export const GET_CLIENT_CONTRACT_REQUEST_COMPLETED = "contracts/GET_CLIENT_CONTRACT_REQUEST_COMPLETED";

// SAVE CLIENT CONTRACT REVIEW
export const SAVE_CLIENT_CONTRACT_REVIEW_REQUEST = "contracts/SAVE_CLIENT_CONTRACT_REVIEW_REQUEST";
export const SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_SUCCESS = "contracts/SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_SUCCESS";
export const SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_FAILURE = "contracts/SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_FAILURE";
export const SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_COMPLETED = "contracts/SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_COMPLETED";

// LIST CLIENT CONTRACT REVIEWS
export const LIST_CLIENT_CONTRACT_REVIEWS_REQUEST = "contracts/LIST_CLIENT_CONTRACT_REVIEWS_REQUEST";
export const LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_SUCCESS = "contracts/LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_SUCCESS";
export const LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_FAILURE = "contracts/LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_FAILURE";
export const LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_COMPLETED = "contracts/LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_COMPLETED";
