// CONTRACTS
export const FETCH_CONTRACTS_REQUEST = "contracts/FETCH_CONTRACTS_REQUEST";
export const FETCH_CONTRACTS_REQUEST_SUCCESS = "contracts/FETCH_CONTRACTS_REQUEST_SUCCESS";
export const FETCH_CONTRACTS_REQUEST_FAILURE = "contracts/FETCH_CONTRACTS_REQUEST_FAILURE";
export const FETCH_CONTRACTS_REQUEST_COMPLETED = "contracts/FETCH_CONTRACTS_REQUEST_COMPLETED";

export const GET_CONTRACT_REQUEST = "contracts/GET_CONTRACT_REQUEST";
export const GET_CONTRACT_REQUEST_SUCCESS = "contracts/GET_CONTRACT_REQUEST_SUCCESS";
export const GET_CONTRACT_REQUEST_FAILURE = "contracts/GET_CONTRACT_REQUEST_FAILURE";
export const GET_CONTRACT_REQUEST_COMPLETED = "contracts/GET_CONTRACT_REQUEST_COMPLETED";

export const SAVE_CONTRACT_REQUEST = "contracts/SAVE_CONTRACT_REQUEST";
export const SAVE_CONTRACT_REQUEST_SUCCESS = "contracts/SAVE_CONTRACT_REQUEST_SUCCESS";
export const SAVE_CONTRACT_REQUEST_FAILURE = "contracts/SAVE_CONTRACT_REQUEST_FAILURE";
export const SAVE_CONTRACT_REQUEST_COMPLETED = "contracts/SAVE_CONTRACT_REQUEST_COMPLETED";

export const UPDATE_CONTRACT_REQUEST = "contracts/UPDATE_CONTRACT_REQUEST";
export const UPDATE_CONTRACT_REQUEST_SUCCESS = "contracts/UPDATE_CONTRACT_REQUEST_SUCCESS";
export const UPDATE_CONTRACT_REQUEST_FAILURE = "contracts/UPDATE_CONTRACT_REQUEST_FAILURE";
export const UPDATE_CONTRACT_REQUEST_COMPLETED = "contracts/UPDATE_CONTRACT_REQUEST_COMPLETED";
