// SAVE CLIENT CONTRACT
export const SAVE_CLIENT_CONTRACT_REQUEST = "contracts/SAVE_CLIENT_CONTRACT_REQUEST";
export const SAVE_CLIENT_CONTRACT_REQUEST_SUCCESS = "contracts/SAVE_CLIENT_CONTRACT_REQUEST_SUCCESS";
export const SAVE_CLIENT_CONTRACT_REQUEST_FAILURE = "contracts/SAVE_CLIENT_CONTRACT_REQUEST_FAILURE";
export const SAVE_CLIENT_CONTRACT_REQUEST_COMPLETED = "contracts/SAVE_CLIENT_CONTRACT_REQUEST_COMPLETED";

// LIST CLIENT CONTRACTS
export const LIST_CLIENT_CONTRACTS_REQUEST = "contracts/LIST_CLIENT_CONTRACTS_REQUEST";
export const LIST_CLIENT_CONTRACTS_REQUEST_SUCCESS = "contracts/LIST_CLIENT_CONTRACTS_REQUEST_SUCCESS";
export const LIST_CLIENT_CONTRACTS_REQUEST_FAILURE = "contracts/LIST_CLIENT_CONTRACTS_REQUEST_FAILURE";
export const LIST_CLIENT_CONTRACTS_REQUEST_COMPLETED = "contracts/LIST_CLIENT_CONTRACTS_REQUEST_COMPLETED";

// GET CONTRACT
export const GET_CONTRACT_REQUEST = "contracts/GET_CONTRACT_REQUEST";
export const GET_CONTRACT_REQUEST_SUCCESS = "contracts/GET_CONTRACT_REQUEST_SUCCESS";
export const GET_CONTRACT_REQUEST_FAILURE = "contracts/GET_CONTRACT_REQUEST_FAILURE";
export const GET_CONTRACT_REQUEST_COMPLETED = "contracts/GET_CONTRACT_REQUEST_COMPLETED";

// GET CONTRACT
export const GET_CONTRACT_WITH_PAYMENTS_REQUEST = "contracts/GET_CONTRACT_WITH_PAYMENTS_REQUEST";
export const GET_CONTRACT_WITH_PAYMENTS_REQUEST_SUCCESS = "contracts/GET_CONTRACT_WITH_PAYMENTS_REQUEST_SUCCESS";
export const GET_CONTRACT_WITH_PAYMENTS_REQUEST_FAILURE = "contracts/GET_CONTRACT_WITH_PAYMENTS_REQUEST_FAILURE";
export const GET_CONTRACT_WITH_PAYMENTS_REQUEST_COMPLETED = "contracts/GET_CONTRACT_WITH_PAYMENTS_REQUEST_COMPLETED";

// SAVE CLIENT CONTRACT REVIEW
export const SAVE_CLIENT_CONTRACT_REVIEW_REQUEST = "contracts/SAVE_CLIENT_CONTRACT_REVIEW_REQUEST";
export const SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_SUCCESS = "contracts/SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_SUCCESS";
export const SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_FAILURE = "contracts/SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_FAILURE";
export const SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_COMPLETED = "contracts/SAVE_CLIENT_CONTRACT_REVIEW_REQUEST_COMPLETED";

// LIST CLIENT CONTRACT REVIEWS
export const LIST_CLIENT_CONTRACT_REVIEWS_REQUEST = "contracts/LIST_CLIENT_CONTRACT_REVIEWS_REQUEST";
export const LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_SUCCESS = "contracts/LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_SUCCESS";
export const LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_FAILURE = "contracts/LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_FAILURE";
export const LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_COMPLETED = "contracts/LIST_CLIENT_CONTRACT_REVIEWS_REQUEST_COMPLETED";

// FAV_REQUEST
export const FAV_REQUEST = "contracts/FAV_REQUEST";

// COMMENTS
export const COMMENT_REQUEST = "contracts/COMMENT_REQUEST";

// LIST_CONTRACT_COMMENTS
export const LIST_CONTRACT_COMMENTS_REQUEST = "contracts/LIST_CONTRACT_COMMENTS_REQUEST";
export const LIST_CONTRACT_COMMENTS_REQUEST_SUCCESS = "contracts/LIST_CONTRACT_COMMENTS_REQUEST_SUCCESS";
export const LIST_CONTRACT_COMMENTS_REQUEST_FAILURE = "contracts/LIST_CONTRACT_COMMENTS_REQUEST_FAILURE";
export const LIST_CONTRACT_COMMENTS_REQUEST_COMPLETED = "contracts/LIST_CONTRACT_COMMENTS_REQUEST_COMPLETED";

// ADD_CONTRACT_COMMENTS
export const ADD_CONTRACT_COMMENTS_REQUEST = "contracts/ADD_CONTRACT_COMMENTS_REQUEST";
export const ADD_CONTRACT_COMMENTS_REQUEST_SUCCESS = "contracts/ADD_CONTRACT_COMMENTS_REQUEST_SUCCESS";
export const ADD_CONTRACT_COMMENTS_REQUEST_FAILURE = "contracts/ADD_CONTRACT_COMMENTS_REQUEST_FAILURE";
export const ADD_CONTRACT_COMMENTS_REQUEST_COMPLETED = "contracts/ADD_CONTRACT_COMMENTS_REQUEST_COMPLETED";
