// CELEBRITIES
export const FETCH_CELEBRITIES_REQUEST = "restCountries/FETCH_CELEBRITIES_REQUEST";
export const FETCH_CELEBRITIES_REQUEST_SUCCESS = "restCountries/FETCH_CELEBRITIES_REQUEST_SUCCESS";
export const FETCH_CELEBRITIES_REQUEST_FAILURE = "restCountries/FETCH_CELEBRITIES_REQUEST_FAILURE";
export const FETCH_CELEBRITIES_REQUEST_COMPLETED = "restCountries/FETCH_CELEBRITIES_REQUEST_COMPLETED";
