export const AVAILABLE_CURRENCIES = [
  {
    name: "ARS",
    label: "Pesos Argentinos",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/ar.webp",
    document_name: "DNI o CUIT",
    decimal_separator: ",",
    thousand_separator: ".",
    round: "100",
  },
  {
    name: "BRL",
    label: "Real Brasileño",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/br.webp",
    document_name: "CPF o CNPJ",
    decimal_separator: ",",
    thousand_separator: ".",
    round: "5",
  },
  {
    name: "CAD",
    label: "Dólares Canadienses",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/ca.webp",
    document_name: "SIN",
    decimal_separator: ".",
    thousand_separator: ",",
    round: "1",
  },
  {
    name: "CLP",
    label: "Pesos Chilenos",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/cl.webp",
    document_name: "CI/RUT",
    decimal_separator: ",",
    thousand_separator: ".",
    round: "1000",
  },
  {
    name: "COP",
    label: "Pesos Colombianos",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/co.webp",
    document_name: "CC",
    decimal_separator: ",",
    thousand_separator: ".",
    round: "1000",
  },
  {
    name: "EUR",
    label: "Euros",
    symbol: "€",
    implemented_by_dlocal: false,
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/1200px-Flag_of_Europe.svg.png",
    document_name: "DNI",
    decimal_separator: ",",
    thousand_separator: ".",
    round: "1",
  },
  {
    name: "DOP",
    label: "Pesos Dominicanos",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/do.webp",
    document_name: "Cédula",
    decimal_separator: ",",
    thousand_separator: ".",
    round: "50",
  },
  {
    name: "MXN",
    label: "Pesos Mexicanos",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/mx.webp",
    document_name: "CURP",
    decimal_separator: ".",
    thousand_separator: ",",
    round: "5",
  },
  {
    name: "PEN",
    label: "Sol",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/pe.webp",
    document_name: "DNI",
    decimal_separator: ",",
    thousand_separator: ".",
    round: "5",
  },
  {
    name: "PYG",
    label: "Pesos Paraguayos",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/py.webp",
    document_name: "CI",
    decimal_separator: ",",
    thousand_separator: ".",
    round: "10000",
  },
  {
    name: "USD",
    label: "Dólares",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/us.webp",
    document_name: "SSN",
    decimal_separator: ".",
    thousand_separator: ",",
    round: "1",
  },
  {
    name: "UYU",
    label: "Pesos Uruaguayos",
    symbol: "$",
    implemented_by_dlocal: false,
    flag: "https://flagcdn.com/w20/uy.webp",
    document_name: "CI",
    decimal_separator: ",",
    thousand_separator: ".",
    round: "50",
  },
];
