export const HIDE_VIDEO_CALLS_RESEARCH = "HIDE_VIDEO_CALLS_RESEARCH";
export const CELEBRITY_PROFILE_VERSION = "CELEBRITY_PROFILE_VERSION";
export const DISCOUNT_COUPON_BANNER_FINISH_TIME = "discount_coupon_banner";
