// SUBSCRIPTION CELEBRITY ALARM
export const GET_USERS_SUBSCRIPTIONS_ALARMS_REQUEST =
  "subscription-celebrity-alarm/GET_USERS_SUBSCRIPTIONS_ALARMS_REQUEST";
export const GET_USERS_SUBSCRIPTIONS_ALARMS_REQUEST_SUCCESS =
  "subscription-celebrity-alarm/GET_USERS_SUBSCRIPTIONS_ALARMS_REQUEST_SUCCESS";
export const GET_USERS_SUBSCRIPTIONS_ALARMS_REQUEST_FAILURE =
  "subscription-celebrity-alarm/GET_USERS_SUBSCRIPTIONS_ALARMS_REQUEST_FAILURE";
export const GET_USERS_SUBSCRIPTIONS_ALARMS_REQUEST_COMPLETED =
  "subscription-celebrity-alarm/GET_USERS_SUBSCRIPTIONS_ALARMS_REQUEST_COMPLETED";
