const MODEL = "celebrity-subscriptions-benefits";

export const GET_CODE_REQUEST = `${MODEL}/GET_CODE_REQUEST`;
export const GET_CODE_REQUEST_SUCCESS = `${MODEL}/GET_CODE_REQUEST_SUCCESS`;
export const GET_CODE_REQUEST_FAILURE = `${MODEL}/GET_CODE_REQUEST_FAILURE`;
export const GET_CODE_REQUEST_COMPLETED = `${MODEL}/GET_CODE_REQUEST_COMPLETED`;

export const GET_USER_REFERRALS_LIST_REQUEST = `${MODEL}/GET_USER_REFERRALS_LIST_REQUEST`;
export const GET_USER_REFERRALS_LIST_REQUEST_SUCCESS = `${MODEL}/GET_USER_REFERRALS_LIST_REQUEST_SUCCESS`;
export const GET_USER_REFERRALS_LIST_REQUEST_FAILURE = `${MODEL}/GET_USER_REFERRALS_LIST_REQUEST_FAILURE`;
export const GET_USER_REFERRALS_LIST_REQUEST_COMPLETED = `${MODEL}/GET_USER_REFERRALS_LIST_REQUEST_COMPLETED`;
