const MODEL = "my-account";

export const FETCH_USER_FAVORITES_CELEBRITIES = `${MODEL}/FETCH_USER_FAVORITES_CELEBRITIES`;
export const FETCH_USER_FAVORITES_CELEBRITIES_SUCCESS = `${MODEL}/FETCH_USER_FAVORITES_CELEBRITIES_SUCCESS`;
export const FETCH_USER_FAVORITES_CELEBRITIES_FAILURE = `${MODEL}/FETCH_USER_FAVORITES_CELEBRITIES_FAILURE`;
export const FETCH_USER_FAVORITES_CELEBRITIES_COMPLETED = `${MODEL}/FETCH_USER_FAVORITES_CELEBRITIES_COMPLETED`;

export const FETCH_USER_FAVORITES_CONTRACTS = `${MODEL}/FETCH_USER_FAVORITES_CONTRACTS`;
export const FETCH_USER_FAVORITES_CONTRACTS_SUCCESS = `${MODEL}/FETCH_USER_FAVORITES_CONTRACTS_SUCCESS`;
export const FETCH_USER_FAVORITES_CONTRACTS_FAILURE = `${MODEL}/FETCH_USER_FAVORITES_CONTRACTS_FAILURE`;
export const FETCH_USER_FAVORITES_CONTRACTS_COMPLETED = `${MODEL}/FETCH_USER_FAVORITES_CONTRACTS_COMPLETED`;
