const MODEL = "celebrity-sections";

export const FETCH_USER_CELEBRITY_LIKES = `${MODEL}/FETCH_USER_CELEBRITY_LIKES`;
export const FETCH_USER_CELEBRITY_LIKES_SUCCESS = `${MODEL}/FETCH_USER_CELEBRITY_LIKES_SUCCESS`;
export const FETCH_USER_CELEBRITY_LIKES_FAILURE = `${MODEL}/FETCH_USER_CELEBRITY_LIKES_FAILURE`;
export const FETCH_USER_CELEBRITY_LIKES_COMPLETED = `${MODEL}/FETCH_USER_CELEBRITY_LIKES_COMPLETED`;
export const FETCH_USER_CELEBRITY_LIKES_CLEAN_UP = `${MODEL}/FETCH_USER_CELEBRITY_LIKES_CLEAN_UP`;

export const ADD_OR_REMOVE_LIKE = `${MODEL}/ADD_OR_REMOVE_LIKE`;
export const ADD_OR_REMOVE_LIKE_SUCCESS = `${MODEL}/ADD_OR_REMOVE_LIKE_SUCCESS`;
export const ADD_OR_REMOVE_LIKE_FAILURE = `${MODEL}/ADD_OR_REMOVE_LIKE_FAILURE`;
export const ADD_OR_REMOVE_LIKE_COMPLETED = `${MODEL}/ADD_OR_REMOVE_LIKE_COMPLETED`;

export const FETCH_USER_CELEBRITY_LIKES_WITH_OFFSET = `${MODEL}/FETCH_USER_CELEBRITY_LIKES_WITH_OFFSET`;
export const FETCH_USER_CELEBRITY_LIKES_WITH_OFFSET_SUCCESS = `${MODEL}/FETCH_USER_CELEBRITY_LIKES_WITH_OFFSET_SUCCESS`;
export const FETCH_USER_CELEBRITY_LIKES_WITH_OFFSET_FAILURE = `${MODEL}/FETCH_USER_CELEBRITY_LIKES_WITH_OFFSET_FAILURE`;
export const FETCH_USER_CELEBRITY_LIKES_WITH_OFFSET_COMPLETED = `${MODEL}/FETCH_USER_CELEBRITY_LIKES_WITH_OFFSET_COMPLETED`;
