export const FETCH_USER_CELEBRITY_LIKES =
  "celebrity-sections/FETCH_USER_CELEBRITY_LIKES";
export const FETCH_USER_CELEBRITY_LIKES_SUCCESS =
  "celebrity-sections/FETCH_USER_CELEBRITY_LIKES_SUCCESS";
export const FETCH_USER_CELEBRITY_LIKES_FAILURE =
  "celebrity-sections/FETCH_USER_CELEBRITY_LIKES_FAILURE";
export const FETCH_USER_CELEBRITY_LIKES_COMPLETED =
  "celebrity-sections/FETCH_USER_CELEBRITY_LIKES_COMPLETED";
